### ISSUE TITLE
Emacs Client doesn't work

### ISSUE THREAD

**Issue by CobaltSpace** [Anomalocaridid/handlr-regex#95]
When I have emacsclient set to open a file, nothing happens.

testing with `mimeopen` from `perl-file-mimeinfo` works as expected.

```jsonc
// handlr get text/org --json
{"cmd":"sh -c if [ -n \\\\$*\\ ]; then exec /usr/bin/emacsclient --alternate-editor= --reuse-frame \\\\$@\\; else exec emacsclient --alternate-editor= --create-frame; fi sh","handler":"emacsclient.desktop","name":"Emacs (Client)"}
// handlr get text/org --json | jq
{
  "cmd": "sh -c if [ -n \\\\$*\\ ]; then exec /usr/bin/emacsclient --alternate-editor= --reuse-frame \\\\$@\\; else exec emacsclient --alternate-editor= --create-frame; fi sh",
  "handler": "emacsclient.desktop",
  "name": "Emacs (Client)"
}
```

```desktop
# /usr/share/applications/emacsclient.desktop
[Desktop Entry]
Name=Emacs (Client)
GenericName=Text Editor
Comment=Edit text
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;x-scheme-handler/org-protocol;
Exec=sh -c "if [ -n \\"\\$*\\" ]; then exec /usr/bin/emacsclient --alternate-editor= --reuse-frame \\"\\$@\\"; else exec emacsclient --alternate-editor= --create-frame; fi" sh %F
Icon=emacs
Type=Application
Terminal=false
Categories=Development;TextEditor;
StartupNotify=true
StartupWMClass=Emacs
Keywords=emacsclient;
Actions=new-window;new-instance;

[Desktop Action new-window]
Name=New Window
Exec=/usr/bin/emacsclient --alternate-editor= --create-frame %F

[Desktop Action new-instance]
Name=New Instance
Exec=emacs %F
```
other applications work as expected

**Comment by Anomalocaridid** [comment]
Currently, `handlr-regex` uses the `shlex` crate to split desktop entries' `Exec` fields into a list of strings according to shell parsing rules, which is then used to spawn a command.

In theory, this should be as simple as reworking that part to not split the `Exec` field and use something like the `execute` crate to turn it into a command directly.

Unfortunately I have been rather busy recently and it might be a bit before I get around to fixing this.

**Comment by Anomalocaridid** [comment]
@CobaltSpace Sorry for taking so long, but I finally got around to trying to fix this several days ago.

I can confirm it does have something to do with how the `Exec` field is parsed and how it is messing up the `sh` command. However, what exactly `handlr` is doing wrong is harder to pin down than I originally thought and I cannot figure out how to get it to work.

What other file openers does Emacs Client work with?

I am having trouble reverse-engineering what `mimeopen` is doing differently because I am not very familiar with Perl.

**Comment by Anomalocaridid** [comment]
After some investigation, to my surprise, `xdg-open` and `mimeo` also do not work with Emacs Client. Could you confirm this on your end?

Either way, it will not affect my willingness to fix this, but it would be helpful to confirm that `mimeopen` is the odd one out in this regard.

**Comment by CobaltSpace** [comment]
I did some tests, opening org mode files. Here is what worked for me:
```
$ xdg-open file.org
Opening "file.org" with Emacs (Client)  (text/org)

$ mimeopen file.org
Opening "file.org" with Emacs (Client)  (text/org)

$ gio open file.org
```

What didn't work:

```
$ mimeo file.org
sh: line 1: [: missing `]'

$ handlr open file.org
```

So for some reason `xdg-open` is working for me but not you.

**Comment by Anomalocaridid** [comment]
Hello, sorry for taking a month to get back on this. Did you install Emacs Client through Nix's home-manager?

If so, apparently, this is probably caused by an [upstream bug](https://github.com/nix-community/home-manager/issues/4163). Apparently, the upstream `emacsclient.desktop` file is broken, but this can be fixed by setting `services.emacs.client.enable = true`. I can confirm this fix works on my end, could you try it?

**Comment by Anomalocaridid** [comment]
I haven't received a response in about a month and as far as I can tell, the problem has been resolved. If anyone still has this problem, feel free to say something and I'll reopen this issue.

**Comment by Frestein** [comment]
> I haven't received a response in about a month and as far as I can tell, the problem has been resolved. If anyone still has this problem, feel free to say something and I'll reopen this issue.


The problem is still relevant, I'm experiencing the same issue. Nothing opens when I select `emacsclient`.

Arch Linux. Mime [config](https://github.com/Frestein/dotfiles/blob/main/dot_config/private_mimeapps.list).

**Comment by Frestein** [comment]
> I suspect this may have to do with character escaping in the Exec line

Yep! Works correctly:
```bash
Exec=sh -c 'if [ $# -gt 0 ]; then exec /usr/bin/emacsclient --alternate-editor="" --reuse-frame "$@"; else exec emacsclient --alternate-editor="" --create-frame; fi' sh %F
```

**Comment by khaalidrafi** [comment]
`xdg-open` doesn't work either. So, maybe, an upstream issue.
